### ISSUE TITLE
usosinstances - encrypt with AES consumer key&secret

### ISSUE THREAD

**Issue by smola222** [dzizes/staraio#93]

**Comment by smola222** [comment]
przy probie parowania usosa wyjątek z /api/usoses

[E 160229 21:39:11 web:1524] Uncaught exception GET /api/usoses (::1)
    HTTPServerRequest(protocol='http', host='localhost:8881', method='GET', uri='/api/usoses', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Accept-Language': 'en-US,en;q=0.8,pl;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8881', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': 'USER_SECURE_COOKIE=null'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1613, in future_complete
        f.result()
      File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/doc/Documents/PycharmProjects/staraio/staraapi/handlers/handlers_api.py", line 92, in get
        data = yield self.get_usoses()
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/Users/doc/Documents/PycharmProjects/staraio/staraapi/handlers/handlers_api.py", line 68, in get_usoses
        usos = self.aes.decrypt_usos(usos)
      File "/Users/doc/Documents/PycharmProjects/staraio/staracommon/AESCipher.py", line 48, in decrypt_usos
        dictionary[key] = self.decrypt(value)
      File "/Users/doc/Documents/PycharmProjects/staraio/staracommon/AESCipher.py", line 41, in decrypt
        return self._unpad(cipher.decrypt(enc[AES.block_size:])).decode(self.encoding)
      File "/Users/doc/Library/Python/2.7/lib/python/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
        return self._cipher.decrypt(ciphertext)
    ValueError: Input strings must be a multiple of 16 in length
[E 160229 21:39:11 web:1946] 500 GET /api/usoses (::1) 11.46ms

**Comment by smola222** [comment]
# usos = self.aes.decrypt_usos(usos)

wykomentowanie działą, czyli przed włożeniem do tabelek trzeba by to zaszyforwąc - o tym zapomniałeś :)

**Comment by smola222** [comment]
po wyczyszczeni bazy działa ok.
